config/routes.rb
Njooh::Application.routes.draw do

  resources :sellables
  
  resources :places do
    resources :reviews
  end

  resources :blogposts do
    resources :comments
  end

  get "home/index"
  get 'tags/:tag', to: 'blogposts#blogfeed', as: :tag
  
  match '/about',to: 'home#about'
  match '/careers',to: 'home#careers'
  match '/developer',to: 'home#developer'
  match '/contact',to: 'home#contact'
  match '/blogfeed',to: 'blogposts#blogfeed'
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end
  
   namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

  root :to => 'home#index'

end

app/views/layouts/general/_footer.html.erb
<footer>
	<div id="copyright">
	  <div class="row full-width">
	    <div class="large-4 columns">
	      <p>&copy; 2013 Njooh.</p>
	    </div>
	  </div>
	</div>
</footer>

app/views/layouts/general/_header.html.erb
<header>
      <nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Njooh", root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
     
      <% if user_signed_in? %>
      	
		<li class="active">
      		<%= link_to "NjooBuzz", home_index_path %>
      	</li> 
      	     
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Blogs", blogfeed_path %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Njooh Places", places_path %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li class="has-dropdown"><a href="#">My Account</a>

        <ul class="dropdown">
          <li>
          	<!--For dev purposes only.Remove later -->
    		<%= link_to('Users', users_path) %>
    	  </li>
        	
          <li>
    		<%= link_to('Edit Profile', edit_user_registration_path) %>
    	  </li>
    	  
          <li class="divider"></li>
          
		  <li>
    		<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    	  </li>
    	  
    	  <li class="divider"></li>
    	  
        </ul>
      </li>
      	
      	
    	
  	 <% else %>
  	 	
    	<li class="active">
    		<%= link_to('Login', new_user_session_path)  %>
    	</li>
    	
    	<li class="divider"></li>
    	<li>
    		<%= link_to('Sign up', new_user_registration_path)  %>
    	</li>
  	<% end %>
      
      <li class="divider"></li>
     
    </ul>

	<% if user_signed_in? %>
	    <!-- Right Nav Section -->
	    <ul class="right">
	      <li class="divider hide-for-small"></li>
	  
	      <li class="has-form">
	        <form>
	          <div class="row collapse">
	            <div class="small-8 columns">
	              <input type="text" placeholder="Search Njooh">
	            </div>
	            <div class="small-4 columns">
	              <a href="#" class="button">Search</a>
	            </div>
	          </div>
	        </form>
	      </li>
	      <li class="divider show-for-small"></li>
	      
	    </ul>
    <% end %>    
  </section>
</nav>
</header>

app/views/layouts/general/_places.html.erb
<h2 class="subheader">
	Njooh Places
</h2>
<h6 class="page-header">
	Do you run a pub,hotel, restaurant or a tourists' resort? Reach out to thousands of customers in 
	3 easy steps.
</h6>

<div class="large-4 columns">
	<%= image_tag('one.jpg') %>
	<p> Go to Njooh Places, Create a Place. </p>
</div>

<div class="large-4 columns">
	<%= image_tag('two.jpg') %>
	<p>Fill out information about your place.</p>
</div>

<div class="large-4 columns">
	<%= image_tag('three.jpg') %>
	<p>Reach out to millions.</p>
</div>

app/views/layouts/general/_slideshow.html.erb
<!-- Orbit Container -->
<div class="orbit-container">
  <ul data-orbit="" class="orbit-slides-container">
    <li>
  
      <%= image_tag('pic1.jpg') %>
      <div class="orbit-caption">
      	<p>
      		Uhuru Park,Nairobi.
      	</p>
      </div>
    </li>
    <li class="active">
      <%= image_tag('pic2.jpg') %>
      <div class="orbit-caption">
      	<p>
      		Central Park,Nairobi.
      	</p>
      </div>
    </li>
    <li>
      <%= image_tag('pic6.jpg') %>
      <div class="orbit-caption">
      	<p>
      		City Market, Nairobi.
      	</p>
      </div>
    </li>
    <li>
      <%= image_tag('pic4.jpg') %>
      <div class="orbit-caption">
      	<p>
      		Imax,Nairobi.
      	</p>
      </div>
    </li>
    <li>
      <%= image_tag('pic5.jpg') %>
      <div class="orbit-caption">
      	<p>
      		Inside IMax,Nairobi.
      	</p>
      </div>
    </li>
    <li>
    	<%= image_tag('njooh.jpg') %>
      
      <div class="orbit-caption">
      	<p>
      	Njooh is an interactive travel platform that incorporates information, 
      	blogs and reviews about places in an easily accessible database for a traveler.
      </p>
      </div>
    </li>
  </ul>
</div>