config/routes.rb
Njooh::Application.routes.draw do

  resources :sellables
  
  resources :places do
    resources :reviews
  end

  resources :blogposts do
    resources :comments
  end

  get "home/index"
  get 'tags/:tag', to: 'blogposts#blogfeed', as: :tag
  
  match '/about',to: 'home#about'
  match '/careers',to: 'home#careers'
  match '/developer',to: 'home#developer'
  match '/contact',to: 'home#contact'
  match '/blogfeed',to: 'blogposts#blogfeed'
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end
  
   namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

  root :to => 'home#index'

end

app/views/layouts/admin/_footer.html.erb
<footer>
	<div id="copyright">
	  <div class="row full-width">
	    <div class="large-4 columns">
	      <p>&copy; 2013 Njooh Systems ,Ltd.</p>
	    </div>
	    <div class="large-8 columns">
	      <ul class="inline-list right">
	        <li>
	        	<%= link_to('Work @ Njooh', careers_path) %>
	        </li>
	        <li>
	        	<%= link_to('About Us', about_path) %>
	        </li>
	        <li>
	        	<%= link_to('Developer', developer_path) %>
	        </li>
	        <li>
	        	<%= link_to('Contact Us', contact_path) %>
	        </li>
	      </ul>
	    </div>
	  </div>
	</div>
</footer>

app/views/layouts/admin/_header.html.erb
<header>
      <nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "Njooh", root_path %></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Left Nav Section -->
    <ul class="left">
      <li class="divider"></li>
     
      <% if user_signed_in? %>
      	
		<li class="active">
      		<%= link_to "Admin NjooBuzz", '#' %>
      	</li> 
      	     
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Admin Blogs", '#' %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Admin Music", '#' %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Admin Places", '#' %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li >
      		<%= link_to "Admin nMaps", '#' %>
      	</li>
      	
      	<li class="divider"></li>
      	
      	<li class="has-dropdown"><a href="#">Admin Account</a>

        <ul class="dropdown">
        	
          <li>
    		<%= link_to('Edit My Account', edit_user_registration_path) %>
    	  </li>
    	  
          <li class="divider"></li>
          
          <li>
    		<%= link_to('Create New Admin',  new_admin_user_path) %>
    	  </li>
    	  
          <li class="divider"></li>
          <li>
    		<%= link_to('Manage Users', admin_users_path) %>
    	  </li>
    	  
          <li class="divider"></li>
          
		  <li>
    		<%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>
    	  </li>
    	  
    	  <li class="divider"></li>
    	  
        </ul>
      </li>
      	
      	
    	
  	 <% else %>
  	 	
    	<li class="active">
    		<%= link_to('Login', new_user_session_path)  %>
    	</li>
    	
    	<li class="divider"></li>
    	<li>
    		<%= link_to('Sign up', new_user_registration_path)  %>
    	</li>
  	<% end %>
      
      <li class="divider"></li>
     
    </ul>

	<% if user_signed_in? %>
	    <!-- Right Nav Section -->
	    <ul class="right">
	      <li class="divider hide-for-small"></li>
	  
	      <li class="has-form">
	        <form>
	          <div class="row collapse">
	            <div class="small-8 columns">
	              <input type="text" placeholder="Search Njooh">
	            </div>
	            <div class="small-4 columns">
	              <a href="#" class="button">Admin Search</a>
	            </div>
	          </div>
	        </form>
	      </li>
	      <li class="divider show-for-small"></li>
	      
	    </ul>
    <% end %>    
  </section>
</nav>
</header>

app/views/layouts/admin/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert-box <%= name == :notice ? "success" : "alert" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/admin/_places.html.erb
<h2 class="subheader">
	Njooh Places
</h2>
<h3 class="subheader">
	Do you run a pub,hotel, restaurant or a tourists' resort? Reach out to thousands of customers in 
	3 easy steps.
</h3>

<div class="large-4 columns">
	<%= image_tag('one.jpg') %>
	<p> Create a places Account. </p>
</div>

<div class="large-4 columns">
	<%= image_tag('two.jpg') %>
	<p>Fill out information about your place.</p>
</div>

<div class="large-4 columns">
	<%= image_tag('three.jpg') %>
	<p>Reach out to millions.</p>
</div>

<div class="row">
	<div class="large-5 columns">
		<h4 class="subheader">Log in into your place.</h4>
		
		<label>Email</label>
        <input type="text" placeholder="Email address.">
        
        <label>Password</label>
        <input type="text" placeholder="Password">
        
        <a href="#" class="button">Log In</a>
	</div>
	
	<div class="large-2 columns">
	</div>
	
	<div class="large-5 columns">
		<h4 class="subheader">Add a place.</h4>
		
		<label>Email</label>
        <input type="text" placeholder="Email address.">
        
        <label>Password</label>
        <input type="text" placeholder="Password.">
        
        <label>Confirm</label>
        <input type="text" placeholder="Confirm Password.">
        
        <a href="#" class="button">Add a Place</a>
	</div>
</div>

app/views/layouts/admin/_slideshow.html.erb
<!-- Orbit Container -->
<div class="orbit-container">
  <ul data-orbit="" class="orbit-slides-container">
    <li>
  
      <%= image_tag('demo3.jpg') %>
      <div class="orbit-caption">...</div>
    </li>
    <li class="active">
      <%= image_tag('demo1.jpg') %>
      <div class="orbit-caption">...</div>
    </li>
    <li>
      <%= image_tag('demo2.jpg') %>
      <div class="orbit-caption">...</div>
    </li>
    <li>
      <%= image_tag('demo3.jpg') %>
      <div class="orbit-caption">...</div>
    </li>
    <li>
      <%= image_tag('demo1.jpg') %>
      <div class="orbit-caption">...</div>
    </li>
  </ul>
</div>