config/routes.rb
Njooh::Application.routes.draw do

  resources :sellables
  
  resources :places do
    resources :reviews
  end

  resources :blogposts do
    resources :comments
  end

  get "home/index"
  get 'tags/:tag', to: 'blogposts#blogfeed', as: :tag
  
  match '/about',to: 'home#about'
  match '/careers',to: 'home#careers'
  match '/developer',to: 'home#developer'
  match '/contact',to: 'home#contact'
  match '/blogfeed',to: 'blogposts#blogfeed'
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end
  
   namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

  root :to => 'home#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div class="alert-box alert">
		<div>
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content">
		<%= wrap(feed_item.content) %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<% if current_user?(feed_item.user) %>
		<%= link_to "delete", feed_item, method: :delete,
										 confirm: "You sure?",
										 title:	feed_item.content %>
	<% end %>
	
</li>

app/views/shared/_micropost_form.html.erb
<div class="row">
	<%= form_for(@micropost) do |f| %>
		<%= render 'shared/error_messages', object: f.object %>
		<div class="field">
	    	<%= f.text_area :content, placeholder: "Compose new micropost...",:rows => 5, :cols => 5%>
	  	</div>
		<div class="actions">
			<%= f.submit "Njooh It!", class: "button" %>
		</div>
	<% end %>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="row">
	<div class="stats">
		<a href="<%= following_user_path(@user) %>">
			<strong id="following" class="stat">
			<%= @user.followed_users.count %>
			</strong>
			following
		</a>
	
		<a href="<%= followers_user_path(@user) %>">
			<strong id="followers" class="stat">
				<%= @user.followers.count %>
			</strong>
			followers
		</a>
	</div>
</div>

app/views/shared/_user_info.html.erb
<div class="row">
	<a href="<%= user_path(current_user) %>">
		<%= gravatar_for current_user%>
	</a>
	
	<h6 class="subheader">
		<%= current_user.name %>
	</h6>
</div>
<div class="row">
	<span>
		<%= link_to "View My Profile", current_user %>
	</span>
</div>
<div class="row">
	<span>
		<%= pluralize(current_user.microposts.count, "Micropost") %>
	</span>
</div>