config/routes.rb
Njooh::Application.routes.draw do

  resources :sellables
  
  resources :places do
    resources :reviews
  end

  resources :blogposts do
    resources :comments
  end

  get "home/index"
  get 'tags/:tag', to: 'blogposts#blogfeed', as: :tag
  
  match '/about',to: 'home#about'
  match '/careers',to: 'home#careers'
  match '/developer',to: 'home#developer'
  match '/contact',to: 'home#contact'
  match '/blogfeed',to: 'blogposts#blogfeed'
  
  authenticated :user do
    root :to => 'home#index'
  end
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  devise_scope :user do
    get "/", :to => "devise/sessions#new"
  end
  
   namespace :admin do
    match '/' => 'users#index'
    resources :users
  end

  root :to => 'home#index'

end

app/models/place.rb
class Place < ActiveRecord::Base
  attr_accessible :data, :description, :location, :name,:assets_attributes,:asset
  
  belongs_to :user
  has_many :place_assets,:dependent => :destroy
  
  has_many :assets
  accepts_nested_attributes_for :assets, :allow_destroy => true
  
  #has_many :sellables, dependent: :destroy
  has_many :reviews, dependent: :destroy
  
  # Do data validations....validate 'data'
  validates :user_id, presence: true
  validates :description, presence: true, length: { maximum: 5000 }
  validates :location, presence: true, length: { maximum: 500 }
  validates :name, presence: true, length: { maximum: 500 }
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  # GET /places
  # GET /places.json
  def index
    @places = Place.all
    @places.each do |place|
      place.assets.build 
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @places }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
    5.times { @place.assets.build }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/new
  # GET /places/new.json
  def new
    @place = Place.new
    5.times { @place.assets.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @place }
    end
  end

  # GET /places/1/edit
  def edit
    @place = Place.find(params[:id])
    5.times { @place.assets.build }
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(params[:place])
    @place.user_id = current_user.id

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render json: @place, status: :created, location: @place }
      else
        format.html { render action: "new" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.json
  def update
    @place = Place.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place = Place.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end
end

app/views/places/_form.html.erb
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
	
	<div class="clearfix">
    <h4>Select Places Images</h4>
    
		<%= f.fields_for :assets do |asset_fields| %>
		
			<% if asset_fields.object.new_record? %>
			<p>
				<%= asset_fields.file_field :asset %>
				<%= asset_fields.text_field :caption, :class => 'text_area',:placeholder =>'Image caption' %>
			</p>
			<% end %>
		
		<% end %>
	</div>
	
	<div class="clearfix">
	    <h4>Place Images</h4>	
		<ul class="thumbnails">
			<%= f.fields_for :assets do |asset_fields| %>
				<% unless asset_fields.object.new_record? %>
				  <li class="span4">
				    <div class="thumbnail">
				      <%= link_to image_tag(asset_fields.object.asset.url(:large)), '#' %>
					  <%= asset_fields.check_box :_destroy %>	
				      <h3>
				      	<%= @place.name %>
				      </h3>
				      <p>
				      	<%= truncate(strip_tags(asset_fields.object.caption),:length => 100) %>
				      </p>
				    </div>
				  </li>
				<% end %>
			<% end %>
		</ul>
	</div>
	
  <div class="actions">
    <%= f.submit %>
  </div>

app/views/places/edit.html.erb
<% provide(:title,'Edit A Place')%>
<div class="row">	
  <div class="large-2 columns">
  	<p></p>
  </div>
  
  <div class="large-8 columns">
  	<h1 class="subheader">Edit Place</h1>
 	
 	<%= form_for @place, :html => { :multipart => true }, :url => places_path, :html => { :class => :form } do |f| -%>
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>

	<%= link_to 'Show', @place %> |
	<%= link_to 'Back', places_path %>

  </div>
  
  <div class="large-2 columns">
  	<p></p>
  </div>
</div>

app/views/places/index.html.erb
<% provide(:title,'Places')%>
<div class="row">
	<div class="large-2 columns">
		<%= link_to 'Create Place', new_place_path, :class =>'custom_btn' %>
	</div>
	<div class="large-8 columns">
		<h1 class="subheader">Njooh Places</h1>
		
		<ul class="thumbnails">
		<% @places.each do |place| %>

			  <li class="span3">
			    <div class="thumbnail">
			      <h3>
			      	<%= place.name %>
			      </h3>
			      <%= link_to image_tag(place.assets.first.asset.url(:large)), place %>

			      <p>
			      	<%= truncate(strip_tags(place.description),:length => 300) %>
			    	<%= link_to 'More Details', place %>
			      </p>
			      
			      <span class="timestamp">
					Created <%= time_ago_in_words(place.created_at) %> ago.
				</span>
				<% if current_user?(place.user) %>
			    	<%= link_to 'Edit', edit_place_path(place) %>
			    	<%= link_to 'Delete Place', place, method: :delete, data: { confirm: 'Are you sure?' } %>
				<% end %>
			      
			    </div>
			  </li>
		<% end %>
	</ul>
		
		<br />
		
		<%= link_to 'Create New Place', new_place_path %>
	</div>
	<div class="large-2 columns">
		<p></p>
	</div>
</div>

app/views/places/new.html.erb
<% provide(:title,'Add A Place')%>
<div class="row">	
  <div class="large-2 columns">
  	<p></p>
  </div>
  
  <div class="large-8 columns">
  	<h1 class="subheader">Create New Place</h1>
 	
 	<%= form_for @place, :html => { :multipart => true }, :url => places_path, :html => { :class => :form } do |f| -%>
	  <%= render :partial => "form", :locals => {:f => f} %>
	<% end -%>

	<%= link_to 'Back', places_path %>
  </div>
  
  <div class="large-2 columns">
  	<p></p>
  </div>
</div>

app/views/places/show.html.erb
<% provide(:title,@place.name)%>
<div class="row">	
  <div class="large-2 columns">
  	<div class="subheader">
  		<p></p>
  	</div>
  	
  </div>
  
  <div class="large-8 columns">
	<p id="notice"><%= notice %></p>
	<h2 class="subheader">
	  <%= @place.name %>
	</h2>
	<div class="row">
		<div class=" small-8 columns">
			<!-- Orbit Container -->
			<%= form_for @place, :html => { :multipart => true }, :url => place_path(@place), :html => { :class => "edit_property", :id => "edit_property" } do |f| -%>
	  				<input name="_method" type="hidden" value="put" />
			<div class="orbit-container">
			  <ul data-orbit="" class="orbit-slides-container">
			  	
			  	<!--Loop for adding images to slideshow -->
			  	<%=f.fields_for :assets do |asset_fields| %>
					<% unless asset_fields.object.new_record? %>
				  		<li>
					      <%= link_to image_tag(asset_fields.object.asset.url(:large)), '#' %>
						  <div class="orbit-caption">
						  		<%= truncate(strip_tags(asset_fields.object.caption),:length => 100) %>
						  </div>
					  </li>
					<% end %>
				<% end %>
				
			  </ul>
			</div>
			<% end -%>
	
		</div>
		<div class="small-4 columns">
			<p>
			  <h6 class="subheader">About Us:</h6>
			  <br />
			  <%= @place.description %>
			</p>
			<p>
			  <h6 class="subheader">Location:</h6>
			  <%= @place.location %>
			</p>
		</div>
	</div>
	<div class="row">
		<h3 class="subheader">Customer Reviews.</h3>
		<ul class="reviews">
			<% @place.reviews.each do |review| %>
			  <li class="microposts">
			  	<p class="subheader">
			  		<strong>Reviewer: </strong>
			  		 <%= review.reviewer %>
			  	</p>
			    <p class="quote">
			    	 <%= review.content %>
			    </p>
			    
			    <span class="timestamp">
					Posted <%= time_ago_in_words(review.created_at) %> ago.
				</span>
				<p>
					<% if current_user?(review.place.user) %>
				  		<%= link_to 'Delete Review', [review.place, review],
				               method: :delete,
				               data: { confirm: 'Are you sure?' } %>
				    <% end %>
				</p>
			  </li>
			<% end %>
		</ul>
		
		<h5 class="subheader">Add a Review:</h5>
		<%= render "reviews/form" %>
	</div>
	

	
	<%= link_to 'Edit', edit_place_path(@place) %> |
	<%= link_to 'Back', places_path %>
	

  </div>
  
  <div class="large-2 columns">
  	<p></p>
  </div>
</div>